alwaysReplace: true
customLabels:
  - text: 'fix'
    label: 'fix'
  - text: 'feature'
    label: 'feature'
  - text: 'feat'
    label: 'feature'
  - text: 'bug'
    label: 'fix'
  - text: 'doc'
    label: 'document'
searchBody: false
